version: '3.8'

services:
  db:
    image: postgres:15
    container_name: petrel_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: petrel
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petrel_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petrel_net

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    command: [
               "-path", "/migrations",
               "-database", "postgres://petrel:password@db:5432/petrel_local?sslmode=disable",
               "up"
    ]
    networks:
      - petrel_net

volumes:
  postgres_data:

networks:
  petrel_net: