version: '3.8'

services:
  db:
    image: postgres:15
    container_name: petrel_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petrel_net

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    command: [
               "-path", "/migrations",
               "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable",
               "up"
    ]
    networks:
      - petrel_net

volumes:
  postgres_data:

networks:
  petrel_net: