env:    "local"
port:   "8080"
cors:
  allow_origins:
    - "http://localhost:8000"
db:
  host:       "localhost"
  port:       5432
  user:       petrel
  password:   password
  dbname:     petrel_local
  sslmode:    disable
notion:
  client_id:      "local-client-id"
  client_secret:  "local-client-secret"
  state_secret:   "local-secret"
  redirect_uri:   "http://localhost:8080/notion/auth/callback"
auth0:
  domain:           "auth0-domain-id"
  client_id:        "local-client-id"
  client_secret:    "local-client-secret"
  connection:       "email"
  redirect_uri:     "http://localhost:8080/auth/callback"
  state_secret:     "local-secret" #TODO: Add state_secret to Secret Manager