env: dev
port: "8080"
cors:
  allow_origins:
    - "http://localhost:8000" #TODO: for testing. change once frontend is up
db:
  host: 10.10.0.3
  name: petrel-dev-db
  port: 5432
  user: postgres
  sslmode: require

notion:
  redirect_uri: "https://petrel-rxvkzfyn3q-uc.a.run.app/notion/auth/callback"