// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Integration struct {
	ID           uuid.UUID          `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Service      string             `json:"service"`
	AccessToken  string             `json:"access_token"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	TokenType    pgtype.Text        `json:"token_type"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type NotionIntegration struct {
	ID               uuid.UUID          `json:"id"`
	IntegrationID    uuid.UUID          `json:"integration_id"`
	WorkspaceID      string             `json:"workspace_id"`
	WorkspaceName    pgtype.Text        `json:"workspace_name"`
	WorkspaceIcon    pgtype.Text        `json:"workspace_icon"`
	BotID            pgtype.Text        `json:"bot_id"`
	NotionUserID     pgtype.Text        `json:"notion_user_id"`
	NotionUserName   pgtype.Text        `json:"notion_user_name"`
	NotionUserAvatar pgtype.Text        `json:"notion_user_avatar"`
	NotionUserEmail  pgtype.Text        `json:"notion_user_email"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	IsActive    pgtype.Bool        `json:"is_active"`
	Provider    pgtype.Text        `json:"provider"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
