// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notion_integrations.sql

package models

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotionIntegration = `-- name: CreateNotionIntegration :one
INSERT INTO notion_integrations (
    id,
    integration_id,
    workspace_id,
    workspace_name,
    workspace_icon,
    bot_id,
    notion_user_id,
    notion_user_name,
    notion_user_avatar,
    notion_user_email
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
         )
    RETURNING id, integration_id, workspace_id, workspace_name, workspace_icon, bot_id, notion_user_id, notion_user_name, notion_user_avatar, notion_user_email, created_at
`

type CreateNotionIntegrationParams struct {
	ID               uuid.UUID   `json:"id"`
	IntegrationID    uuid.UUID   `json:"integration_id"`
	WorkspaceID      string      `json:"workspace_id"`
	WorkspaceName    pgtype.Text `json:"workspace_name"`
	WorkspaceIcon    pgtype.Text `json:"workspace_icon"`
	BotID            pgtype.Text `json:"bot_id"`
	NotionUserID     pgtype.Text `json:"notion_user_id"`
	NotionUserName   pgtype.Text `json:"notion_user_name"`
	NotionUserAvatar pgtype.Text `json:"notion_user_avatar"`
	NotionUserEmail  pgtype.Text `json:"notion_user_email"`
}

func (q *Queries) CreateNotionIntegration(ctx context.Context, arg CreateNotionIntegrationParams) (NotionIntegration, error) {
	row := q.db.QueryRow(ctx, createNotionIntegration,
		arg.ID,
		arg.IntegrationID,
		arg.WorkspaceID,
		arg.WorkspaceName,
		arg.WorkspaceIcon,
		arg.BotID,
		arg.NotionUserID,
		arg.NotionUserName,
		arg.NotionUserAvatar,
		arg.NotionUserEmail,
	)
	var i NotionIntegration
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.WorkspaceID,
		&i.WorkspaceName,
		&i.WorkspaceIcon,
		&i.BotID,
		&i.NotionUserID,
		&i.NotionUserName,
		&i.NotionUserAvatar,
		&i.NotionUserEmail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotionIntegrationByIntegrationID = `-- name: DeleteNotionIntegrationByIntegrationID :exec
DELETE FROM notion_integrations
WHERE integration_id = $1
`

func (q *Queries) DeleteNotionIntegrationByIntegrationID(ctx context.Context, integrationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotionIntegrationByIntegrationID, integrationID)
	return err
}

const getNotionIntegrationByIntegrationID = `-- name: GetNotionIntegrationByIntegrationID :one
SELECT id, integration_id, workspace_id, workspace_name, workspace_icon, bot_id, notion_user_id, notion_user_name, notion_user_avatar, notion_user_email, created_at FROM notion_integrations
WHERE integration_id = $1
`

func (q *Queries) GetNotionIntegrationByIntegrationID(ctx context.Context, integrationID uuid.UUID) (NotionIntegration, error) {
	row := q.db.QueryRow(ctx, getNotionIntegrationByIntegrationID, integrationID)
	var i NotionIntegration
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.WorkspaceID,
		&i.WorkspaceName,
		&i.WorkspaceIcon,
		&i.BotID,
		&i.NotionUserID,
		&i.NotionUserName,
		&i.NotionUserAvatar,
		&i.NotionUserEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getNotionIntegrationByWorkspaceID = `-- name: GetNotionIntegrationByWorkspaceID :one
SELECT id, integration_id, workspace_id, workspace_name, workspace_icon, bot_id, notion_user_id, notion_user_name, notion_user_avatar, notion_user_email, created_at FROM notion_integrations
WHERE workspace_id = $1
`

func (q *Queries) GetNotionIntegrationByWorkspaceID(ctx context.Context, workspaceID string) (NotionIntegration, error) {
	row := q.db.QueryRow(ctx, getNotionIntegrationByWorkspaceID, workspaceID)
	var i NotionIntegration
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.WorkspaceID,
		&i.WorkspaceName,
		&i.WorkspaceIcon,
		&i.BotID,
		&i.NotionUserID,
		&i.NotionUserName,
		&i.NotionUserAvatar,
		&i.NotionUserEmail,
		&i.CreatedAt,
	)
	return i, err
}
